version: '3.7'

services:
    db:
        container_name: postgres-vs
        image: postgres:15.2
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DATABASE}
        ports:
            - '${POSTGRES_PORT}:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - vs-backend

    redis:
        container_name: redis-vs
        image: redis:5.0
        restart: always
        ports:
            - ${REDIS_PORT}:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - vs-backend

volumes:
    postgres_data:
    redis_data:

networks:
    vs-backend:
